plugins {
    id 'com.android.application'
}

android {
    namespace 'com.joselofarias.nightzuku.monitor'
    defaultConfig {
        applicationId 'com.joselofarias.nightzuku.monitor'
        minSdk 29
        versionCode 3
        versionName '1.2.0'
    }
    buildFeatures {
        buildConfig false
    }
    signingConfigs {
        sign
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.sign
        }
    }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
}

apply from: rootProject.file('signing.gradle')
